version: 1.0.{build}
build: off
skip_tags: false
clone_depth: 1

test_script:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        $version = $env:APPVEYOR_REPO_TAG_NAME
    }
    else
    {
        $version = "0.0.1-dev$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))"
    }
    & dotnet test -c Release /p:Version=$version

artifacts:
- path: output\*.*
  name: packages

deploy:
  provider: NuGet
  api_key:
    secure: q/AoeMJ+wWYs32mgAU7lYeerLrZtq9m8GERiCN+fJ8CJISiuchfBiMK+zWJPVVc8
  skip_symbols: false
  on:
    branch: master
    appveyor_repo_tag: true